waypoints:
  - name: "Goal_1"
    position:
      x: 0.0
      y: 3.0
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
  - name: "Goal_2"
    position:
      x: 6.0
      y: 4.0
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 0.523
  - name: "Goal_3"
    position:
      x: 6.5
      y: -1.4
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 3.14
  - name: "Goal_4"
    position:
      x: -1.6
      y: -2.5
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 1.310
  - name: "explore"
    position:
      x: 3.8
      y: 0.1
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: -1.57
  - name: "explore"
    position:
      x: 9.38
      y: 4.30
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: -1.57
  - name: "explore"
    position:
      x: 9.4
      y: -3.89
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: -1.57
  - name: "explore"
    position:
      x: 6.34
      y: -4.76
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: -1.57
  - name: "explore"
    position:
      x: -7.49
      y: -4.10
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: -1.57
  - name: "explore"
    position:
      x: -8.79
      y: 0.345
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: -1.57
  - name: "aruco"
    position:
      x: -4.0
      y: 0.0
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: -1.57
 


mode:
- strategy: "explore" #path or explore or aruco
